server:
  port: 8080

logging:
  level:
    org:
      thymeleaf: DEBUG
      springframework:
        web: DEBUG

spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
      port: 35729

  application:
    name: son

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce-db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
      chain:
        cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: seancoding275@gmail.com   # đổi thành email của bạn
    password: yugxrhdddpflcilf          # đổi thành mật khẩu/app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
